### PR TITLE
Extra fixes for indoor/outdoor integration 

### LINKED ISSUE #252: 6.2.2 – Integrate Outdoor Routing Engine
•	Use outdoor navigation API or existing outdoor routing system.

### LINKED ISSUE #293: BUG-7: No default location for indoor navigation
**Bug Description**
In the Indoor Maps feature, when a user selects a room to navigate to, there is no default start location provided. The user is not prompted or guided to set one, leaving the navigation in an incomplete state.

**Steps To Reproduce The Bug**
1. Open the app
2. Navigate to the Indoor Map view
3. Select a building and floor
4. Attempt to use indoor navigation without having a location set previously
5. Observe that no default start location is provided

**What Is The Expected Result?**
A default start location should be provided (e.g. current location or last known position) or the user should be clearly prompted to set one before navigation begins.

**What Is The Actual Result?**
Navigation has no start point and the user is given no guidance on how to proceed.

**Current Strategy**
[ ] Fix it now
[x] Fix it later -> BUG WAS FOUND DURING SPRINT 5
[ ] Ignore it

Image

### PR DESCRIPTION
**Pull request by anarostam**
- Integrated the outdoor-to-indoor navigation flow to ensure a seamless transition between navigation modes
- Automatically switches to indoor navigation when a user enters a building
- Added a default indoor starting point at the building entrance to ensure a consistent and valid starting location
- Eliminates cases where indoor navigation could start without a defined position
- Improved the overall transition between outdoor and indoor navigation to make the experience smoother and more intuitive
- Enhances usability by providing a more continuous and smooth navigation flow across environments

Closes #252 
Closes #293

### CODE REVIEW

File: frontend/src/screens/MapScreen.js [hunk 1]
```diff
@@ -464,6 +690,18 @@ export default function MapScreen({ route }) {
     return [...startsWithMatches, ...includesMatches].slice(0, 6);
   }, [activeField, startText, destText, allBuildings]);
 
+  const roomResults = useMemo(() => {
```
Comment (n-noc) [inline frontend/src/screens/MapScreen.js]: Nice use of useMemo here, this keeps the filtering efficient and avoids unnecessary recomputation on re-renders.

File: frontend/src/components/SearchBox.js [hunk 2]
```diff
@@ -91,15 +105,33 @@ function SearchBox({
...
+      {activeField &&
+      (activeField === "start" ? startText : destText).trim().length > 0 &&
+      !shouldShowMyLocationOption &&
+      searchResults.length === 0 &&
+      roomResults.length === 0 && (
         <View style={styles.noResultsContainer}>
           <MaterialIcons name="search-off" size={24} color="#999" />
           <Text style={styles.noResultsText}>
-            No buildings found. Please try again.
+            No buildings found. You can also try a room number.
```
Comment (jana-madhoun) [inline frontend/src/components/SearchBox.js]: Nice changes! The extra fixes for indoor look good. The "not found" message says "You can also try a room number" but room results are already shown separately above it so if someone searches and gets no buildings but there are room matches, they'd never see that message anyway.
