### PR TITLE
Changed the between floor navigation layout

### LINKED ISSUE #284: USABILITY-Fix incorrect multi-floor navigation behavior and improve floor transition guidance
## Problem
The multi-floor indoor navigation system is currently unreliable and confusing for users.

When users search for a destination located on a different floor:
- The system sometimes displays a random room on the current floor instead of the correct destination
- Navigation does not clearly guide users through floor transitions (stairs/elevators)
- The interface includes multiple buttons that are non-functional, redundant, or produce identical results
- Users are presented with too many controls that do not provide meaningful or distinct actions

This creates unnecessary cognitive load and leads to a broken and misleading navigation experience.

## Evidence
- Observed during usability testing (Indoor navigation task)
- Users were unable to successfully navigate to rooms on different floors
- Users were confused by inconsistent or incorrect directions
- Users could not identify how to transition between floors (stairs/elevator unclear)
- Repeated interactions with different buttons produced identical or incorrect outputs
- Users hesitated and expressed uncertainty due to unclear or non-responsive controls

## Proposed Solution
- Fix routing logic to correctly handle multi-floor destinations
- Ensure the correct target room is always selected regardless of floor
- Introduce clear step-by-step guidance for floor transitions (e.g., "Take stairs to Floor 2")
- Visually highlight transition points (stairs/elevators) on the map
- Remove, disable, or refactor non-functional and redundant buttons
- Simplify the interface by reducing the number of controls to only essential actions
- Ensure each control has a clear, distinct, and functional purpose

## Impact
- Resolves critical navigation errors affecting core functionality
- Reduces cognitive overload and improves clarity of the interface
- Improves user trust and confidence in the system
- Reduces confusion and failed tasks for multi-floor navigation
- Provides a clear and reliable path for users moving between floors

Image

### LINKED ISSUE #285: USABILITY-Reduce redundant step-by-step instructions in indoor navigation
## Problem
The indoor navigation feature generates an excessive number of redundant instructions, particularly for simple movements such as walking through a corridor.

In some cases, users are presented with many consecutive instructions (e.g., 10–15 steps) that all indicate continuing in the same direction. This creates unnecessary noise and makes it difficult for users to follow the navigation clearly.

## Evidence
- Observed during usability testing (Indoor navigation task)
- Users received long sequences of nearly identical instructions (e.g., "continue forward")
- Users stopped reading instructions due to repetition
- Increased cognitive load and reduced clarity of navigation steps

## Proposed Solution
- Aggregate consecutive identical or similar instructions into a single step (e.g., "Continue straight for 20 meters")
- Introduce distance-based or segment-based instructions instead of micro-step directions
- Display only meaningful transitions (e.g., turns, stairs, elevators)
- Optionally provide progressive instructions instead of showing all steps at once

## Impact
- Reduces cognitive overload and improves readability of directions
- Makes navigation instructions clearer and easier to follow
- Improves overall user experience for indoor navigation
- Aligns with standard navigation patterns used in modern apps

Image

### PR DESCRIPTION
**Pull request by anarostam**
During usability it was shown that users felt confused while searching a between floor navigation. After new changes it is more clear to the users what to do next. 
Closes #284 
Old Layout:
Screenshot 2026-03-29 at 11 28 30 AM

New Layout:
Screenshot 2026-03-29 at 10 15 02 PM

It was also shown on usability testing, that the indoor navigation shows a lot of repetitive steps. This issue was fixed in this pr and now the navigation steps are more clear.
Closes #285 
Old Layout:
Screenshot 2026-03-29 at 11 28 13 AM
 
New Layout:

Screenshot 2026-03-29 at 10 21 25 PM

### CODE REVIEW

File: frontend/src/utils/pathfinding/navigationJourney.js [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+  const transitionLabel = getTransitionLabel(segment.transitionType);
+  return `Use the ${transitionLabel} in ${getBuildingName(segment.buildingId)} to go from Floor ${getFloorLabel(segment.fromFloor)} to Floor ${getFloorLabel(segment.toFloor)}.`;
+}
+
+function buildOutdoorStageDescription(segment) {
+  return `Exit ${getBuildingName(segment.fromBuildingId)} and continue outside to ${getBuildingName(segment.toBuildingId)}.`;
+}
+
+export function buildJourneyStages(routeSegments, startRoom, destRoom) {
+  const segments = routeSegments ?? [];
```
Comment (jana-madhoun) [inline frontend/src/utils/pathfinding/navigationJourney.js]: buildJourneyStages handles three segment types inline maybe consider extracting each case into its own buildIndoorStage, buildVerticalStage, and buildOutdoorStage helper to keep the function focused and make each segment type easier to test individually.

**Review by jana-madhoun — APPROVED** [review]
Great changes! the updated layout is a clear improvement  and the new UI feels more intuitive and keeps the user in context.
