### PR TITLE
POI crash fix, Changed core logic, added unit tests for that newe logic

### LINKED ISSUE #302: BUG 13 - App Crash due to POI category selection
**Bug Description**
After selecting a POI category (e.g. food), choosing a place, receiving directions, and then opening the POI panel, tapping a category causes the app to crash.

**Steps To Reproduce The Bug**

1. Open the app
2. Navigate to the Map view
3. Select a POI category such as "food"
4. Pick a place from the results
5. View the directions panel
6. Tap the POI button to open the POI panel
7. Tap on a category inside the panel
8. Observe that the app crashes
9. 

**What Is The Expected Result?**
Tapping a category inside the POI panel should filter or update results without causing a crash.

**What Is The Actual Result?**
The app crashes immediately upon tapping a category inside the POI panel when directions are already active.

**Current Strategy**
[x] Fix it now
[ ] Fix it later
[ ] Ignore it

### PR DESCRIPTION
**Pull request by Georges999**
fix(map): stop POI panel crash when switching category after directions
- Clear selected POI when reopening the outdoor POIs panel to avoid stacked UI and extra map updates
- Only set hasRequestedPOIs after a valid POI search origin exists (avoid bad results-mode state)
- Replace FlatList with ScrollView for POI results to avoid VirtualizedList issues inside the bottom sheet
- Use stable unique keys for POI map markers and list rows
- FIXED: fix(map): define loadNearbyPOIs after userCoord so Show on map can run
-useCallback/loadNearbyPOIs and displayedPOIs referenced userCoord before it was declared, so poiOriginCoord was always falsy and the handler returned early. Moved POI memos/callback and the next-class GPS effect below the userCoord assignment.
test(frontend): add OutdoorPoiFilterForm tests; slim POI MapScreen tests
Add unit tests for OutdoorPoiFilterForm (nearest/range, fetchRadius, chips).
Keep poiInfoCTA tests to exported helpers only; drop full MapScreen mounts.
Remove MapScreen.handleGo.test.js to avoid duplicating handleGo.test.js.
fix tests(frontend): repair MapScreen tests and Jest timeout for coverage
Invoke watchUserCoords callback in MapScreen tests so userCoord and POI fetch run.
Raise Jest testTimeout for slow full-app suites under --coverage.
Align null-origin POI test with filter form (no empty list); drop debug log.
changed Codecov.yml to a target of 90% per new tests commited, 96.7% was a default fig and was too high, UI tests dont need that much

closes #302

### CODE REVIEW

File: frontend/src/components/OutdoorPoiFilterForm.js [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+          >
+            <Text style={styles.poiRadiusButtonText}>+</Text>
+          </Pressable>
+        </View>
+      ) : null}
+
+      <Text style={styles.poiPanelSectionLabel}>Category</Text>
+
+      <View style={styles.poiCategoryRow}>
+        {Object.keys(categoryToType).map((category) => {
```
Comment (anarostam) [inline frontend/src/components/OutdoorPoiFilterForm.js]: Looks really good overall 👍🏻 the refactor into `OutdoorPoiFilterForm` makes the code cleaner and easier to follow, and the added tests for the new logic are a nice touch.

One small thing I noticed in `OutdoorPoiFilterForm.js: using Object.keys(categoryToType).map(...)` works, but it ties the UI to the object structure. If that changes, the category order could shift, I think it might be safer to define a fixed list.
Other than that, everything looks solid!
