### PR TITLE
Indoor Directions bug fixes +tests and coverage

### LINKED ISSUE #296: BUG 9: Walking Button Overlaps Room Search Dropdown
**Bug Description**
In the Indoor Directions view, when the room search dropdown appears, the "Walking" mode button overlaps and covers some of the dropdown results, making them difficult to read and select.

**Steps To Reproduce The Bug**
1. Open the app
2. Navigate to the Indoor Map view
3. Tap the destination search bar
4. Type a room name to trigger the dropdown
5. Observe that the "Walking" button overlaps the dropdown list

**What Is The Expected Result?**
The dropdown should appear fully visible above all other UI elements without any overlap from the travel mode button.

**What Is The Actual Result?**
The "Walking" button renders over the dropdown, obscuring some room options.

**Current Strategy**
[ ] Fix it now
[x] Fix it later -> BUG WAS FOUND DURING SPRINT 5
[ ] Ignore it

Image

### LINKED ISSUE #307: BUG 14 -  Indoor Interchange Switch Covers the Clear Button
**Bug Description**
In the Indoor navigation view, the start and end room interchange/swap button overlaps and covers the bottom selection clear button, making it inaccessible to the user.

**Steps To Reproduce The Bug**

1. Open the app
2. Navigate to the Indoor Map view
3. Select a start room and an end room
4. Observe the interchange/swap button position
5. Attempt to tap the clear button at the bottom
6. Observe that the swap button covers it and it cannot be tapped
7. 

**What Is The Expected Result?**
The interchange/swap button and the clear button should not overlap; both should be fully visible and tappable.

**What Is The Actual Result?**
The swap start/end room button renders over the clear button, making the clear button unreachable.

**Current Strategy**
[x] Fix it now
[ ] Fix it later
[ ] Ignore it

### PR DESCRIPTION
**Pull request by Georges999**
Improve Indoor Directions swap control layout and row spacing
Improve Indoor Directions swap control layout and row spacing

Wrap the start and destination rows in a relative block so the interchange
button stays vertically centered between them. Tighten the gap between rows,
move the swap toward the map-pin side, and drop extra destination padding so
the clear control matches the start field.

fix(indoor): keep room search dropdowns inside the card and scrollable
IndoorDirectionsScreen: stack search + results above the Walking row; clip the
dropdown with overflow hidden, scroll overflow in a ScrollView, and cap lines
with ellipsize.

IndoorMapScreen: apply the same clipping, inner scroll, and two-line ellipsis
for the initial room search list.
+tests and coverage

closes #307 
closes #296

### CODE REVIEW

File: frontend/src/screens/IndoorDirectionsScreen.js [hunk 1]
```diff
@@ -555,19 +556,28 @@ export default function IndoorDirectionsScreen({ route, navigation }) {
         {searchQuery.trim().length > 0 && activeField && (
           <View style={styles.searchResultsContainer}>
             {searchResults.length > 0 ? (
-              <View>
+              <ScrollView
+                nestedScrollEnabled
+                keyboardShouldPersistTaps="handled"
+                style={styles.searchResultsScroll}
+                showsVerticalScrollIndicator
+              >
```
Comment (Peter7168) [inline frontend/src/screens/IndoorDirectionsScreen.js]: I dont understand the slicing here, is this to limit the number of resuts or the size of each individual result?
